MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  RES_USE : 1
  TRANS_USE : 1
  RES_MODE : 2
  SRM_LAYER : 2
  MIX_DIM : 768
  PRETRAIN_PATH_R : '/15127306268/wyh/UIS/pth/r101.pth'
  PRETRAIN_PATH_T : '/15127306268/wyh/UIS/pth/restv2_large_224.pth'
  TRANSFORMER_TYPE: 'restv2_large'



INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('msmt17')
  ROOT_DIR: './data'

TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './msmt_ResTV2L_res50_layer2'

